### ISSUE TITLE
Service Failed to start. 31: A device attached to the system is not functioning

### ISSUE THREAD

**Issue by 0x57696c6c** [ReversecLabs/physmem2profit#7] opened 2020-08-21 14:08 UTC
I seem to be having issues with the physmem2profit service on my bare-metal Windows 10 host. Any suggesstions?

Compiled with Microsoft Visual Studio Community 2019 version 16.5.5

Ran on Microsoft Windows Version 10 2004 update:
`.\Physmem2profit.exe --ip 192.168.128.142 -p 80 --verbose`

Attacking machine command:
`python3 physmem2profit --host 192.168.128.142 --port 80 --mode all --driver winpmem --install c:/temp/att_winpmem_64.sys --label foobar`

Receiving the following output from the Windows 10 host after attacking with my Kali machine:
```[*] Registering driver bridges.
[+] Found driver bridge: WinPmem.
[+] Registered command: Install.  
[+] Registered command: Uninstall.  
[+] Registered command: Map.
[+] Registered command: Read.
[*] Starting server on 192.168.128.142:21...
[+] Server Started.
[*] Waiting for a connection...
[+] Connected!
[*] Invoking Command Install for driver WinPmem.
[*] Installing service...
[*] Creating service physmem2profit...
[+] Service created successfully.
[*] Starting service...
[*] Service is stopped. Trying to start it...
[-] Service Failed to start. 31: A device attached to the system is not functioning
[*] Invoking Command Uninstall for driver WinPmem.
[?] Service already stopped.
[+] Successfully unloaded the WinPMem driver.
[*] Exit command received. Terminating.

**Comment by timhir** [comment] 2020-08-21 15:07
Sorry to hear that Physmem2profit isn’t working properly on your system :/. I know it’s not a proper solution but does a reboot help?

**Comment by 0x57696c6c** [comment] 2020-08-21 15:16
The issue persists through a reboot.

**Comment by timhir** [comment] 2020-08-23 16:11
I will try to investigate this at some point. Unfortunately cannot give any guarantees on the schedule :/

**Comment by YOLOP0wn** [comment] 2021-02-03 23:40
Hey, any news on that issue ? Do you know if its related to the windows version / visual studio build, or to the python client install ?

Thanks

**Comment by timhir** [comment] 2021-02-04 07:11
I'm sorry to say that there's no news on this issue. I haven't had any time to work on Physmem2profit and I'm not sure when I have the availability... I promise to look into this issue once I have a chance to work on this again.

If possible, could you test with https://github.com/Velocidex/WinPmem/releases/tag/v4.0.rc1, please? The release notes say it "fixes an issue with the drivers loading on recent Windows versions".

**Comment by YOLOP0wn** [comment] 2021-02-04 08:38
i tried and got this error:

[*] Loading config from config.json
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/physmem2profit/client/physmem2profit/__main__.py", line 65, in <lambda>
    jobs.append(Process(target=lambda: mount.mount(socket, args.driver, args.install)))     # mount will block thread, it need to be handled by child process.
  File "/physmem2profit/client/physmem2profit/mount.py", line 366, in mount
    fuse = FUSE(Physmem(sock, mountpoint, driver, installArguments), mountpoint, nothreads=True, foreground=True)
  File "/physmem2profit/client/physmem2profit/mount.py", line 46, in __init__
    raise Exception(struct.unpack("<%ds" % response, self.socket.recv(response))[0].decode('utf-8'))
Exception: Sending ParseMemoryRuns control code failed, windows error code 87: Paramètre incorrec
Exception ignored in: <function Physmem.__del__ at 0x7f6ba494ea60>
Traceback (most recent call last):
  File "/physmem2profit/client/physmem2profit/mount.py", line 100, in __del__
    response = struct.unpack("<I", received)[0]
struct.error: unpack requires a buffer of 4 bytes


And on server side:

[+] Connected!
[*] Installing service...
[*] Creating service physmem2profit...
[+] Service created successfully.
[*] Starting service...
[*] Service is stopped. Trying to start it...
[+] Driver service started.
[-] Sending ParseMemoryRuns control code failed, windows error code 87: Paramètre incorrect
[*] Service is running. Trying to stop it...
[+] Successfully unloaded the WinPMem driver.


 (ps: well, there's also an issue with acora which seems not installable with python3.9)

**Comment by fersingb** [comment] 2021-03-29 22:38
Same issue as the original one here: `[-] Service Failed to start. 31: A device attached to the system is not functioning`

Not sure how to investigate this, I'd be happy to debug this but I don't know WinAPI very well and didn't manage to get useful logs...

**Comment by fersingb** [comment] 2021-06-23 15:04
Hello,

I tried the most recent driver and got the same issue as @Antho59 , this seems to be caused by a change in the IOCTRL codes. I recompiled the Physmem2profit server with `INFO_IOCTRL = 0x22C40F` and I got past this specific error. However it's still not working. 

After sending the Map command it just hangs there for a while and at some point the python client crashes with "File does not exist: `<path to image.raw>`"

When I add some debug statements in the client, I see the `n` value used in the for loop to build the `runs` array is 0. However in DebugView I see "Memory range runs found: 7", so this seems to mismatch and I don't know why. For now this is beyond my Windows Kernel understanding/knowledge.

@timhir: Any chance you could have a quick look at this? I understand you're probably busy, so maybe if you could give me some pointers I might be able to investigate that further.

Cheers,
Boris

**Comment by timhir** [comment] 2021-06-23 17:01
Thank you for the detailed description, Boris! I apologize that I don’t have time to debug this myself… However, I think I know where the problem is.

Most likely the structure of the data returned by INFO_IOCTRL has changed. Please compare https://github.com/Velocidex/WinPmem/blob/e503038acfa3f4d3469341f6e126ef2958c342c3/kernel/userspace_interface/winpmem_shared.h#L34 with https://github.com/FSecureLABS/physmem2profit/blob/296d8fefecf2c852b955d01bad97f89c3194322f/server/Plugins/WinPmem.cs#L16 and all the other logic for parsing the response from the Winpmem driver.

If you need more advice, could you kindly post a hexdump of the content of `buffer` after the call at https://github.com/FSecureLABS/physmem2profit/blob/296d8fefecf2c852b955d01bad97f89c3194322f/server/Plugins/WinPmem.cs#L66, please :)?

Thank you for taking interest in Physmem2profit and troubleshooting this issue :). This gives me the motivation to create a new and improved version of Physmem2profit once my schedule is less hectic!

**Comment by fersingb** [comment] 2021-06-23 17:08
Hello @timhir,

Indeed I just figured that out, I had to add more KPCs to handle the 64 bits architecture. Now it looks like I'm getting something as I see a .raw file that's 66GB big, however the client seems to be stuck at "Finding LSASS process".

This step is supposed to be fast, isn't it? Is there a way I can monitor the progress and see if it's actually doing something? Should I see multiple "READ" requests between the client/server?

Thanks

**Comment by timhir** [comment] 2021-06-23 17:17
66GB sound high. Does your target have 64GB of RAM?

It could be that Rekall is failing, it’s End Of Life already… Try dumping the memory to a file normally using Winpmem (without Physmem2profit). Run rekall against the image to see is it able to list processes from the image.

**Comment by fersingb** [comment] 2021-06-24 00:07
Yes it's 64GB. Now I'm testing on an other machine that has only 4GB and I see a 4.2GB file, so it matches the memory size and it's still stuck at the same place.

Is it possible that the fuse part is actually broken? How does that part actually work? Maybe I'm seeing a file that's the correct size but it's actually garbage because something else changed in the Winpmem driver? Any way to check that?

Few months ago, when I posted my first comment here I ended up using Winpmem to dump the whole memory and then used physmem2profit to extract the LSASS info from the dump and it worked. I'll give it a try again when I can.

**Comment by timhir** [comment] 2021-06-24 04:01
It’s totally possible that something else has changed in the Winpmem driver too.

You could try opening the raw file in a hex editor and check is it all zeros or something. If you run `strings` against a good raw file you should see plenty of meaningful stuff.

**Comment by ciyi** [comment] 2021-07-23 16:16
> Yes it's 64GB. Now I'm testing on an other machine that has only 4GB and I see a 4.2GB file, so it matches the memory size and it's still stuck at the same place.
> 
> Is it possible that the fuse part is actually broken? How does that part actually work? Maybe I'm seeing a file that's the correct size but it's actually garbage because something else changed in the Winpmem driver? Any way to check that?
> 
> Few months ago, when I posted my first comment here I ended up using Winpmem to dump the whole memory and then used physmem2profit to extract the LSASS info from the dump and it worked. I'll give it a try again when I can.

Hi Boris, how did you dump the lsass process from a winpmem dump using physmem2profit? Im facing the same problem atm. I dumped the memory separately but I now need to extract lsass and volatility doesn't seem to work fine. 
I'd appreciate your response. Thanks!

**Comment by timhir** [comment] 2022-07-27 03:48
Should be fixed now. Thanks, @tothi!

**Closed as completed** 2022-07-27 03:49 UTC
